# CONFIG - Refresh terminal command after updating this file
testMode:     "off"                  # on|off: Display testing helpers

# Installed Gems
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed

# Site settings
title:        "Technology and Choice"
description:  "Building from the First Principle"
url:          "https://technologyandchoice.com" # the base hostname (*Do not close with /)
baseurl:      ""                                # the subpath of your site, e.g. /blog (Use this for Github project page)
author:       "John Ferguson"
twitter:
  username:   "SAFEcrossroads"
social:
  name:       "John Ferguson"
  links:
    -         "https://twitter.com/SAFEcrossroads"
logo:         "/assets/brand/thumbnail.jpg"
lang:     "en"
type:         "website"                         #website | blog
timezone:     "US/Central"

# Build settings
markdown:      kramdown
sass:
  sass_dir:    assets/css/_scss         # default sass_dir
  syntax:      scss                     # scss | sass
  style:       compressed               # nested | expanded | compact | compressed

# Layout
layout:        "responsive"              # static | responsive
topNavbar:     "on"                     # on | off: top fixed nav
logoType:      "image"                   # text | image
gridClass:
  main:        "col-sm-8"
  sidebar:     "col-sm-4"

# Collection
collections:
  docs:
    output: true

# Posting Default
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      image: "/assets/brand/thumbnail.jpg"
  -
    scope:
      type: "posts"
    values:
      image: "/assets/brand/thumbnail.jpg"
      layout: "post"
      author: "John Ferguson"
      tags:   "post"

permalink:     :categories/:year/:month/:title/   #Post URL
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
paginate_path: "/post/page:num/"
paginate:      8

# User
userInfo:
  email:       "simpleton@safecrossroads.net"

# Links
snsLink:
  twitter:     "https://twitter.com/safecrossroads"    # Twitter
  github:      "https://github.com/safecrossroads/technologyandchoice.com"    # Github
  email:       "mailto:info@technologyandchoice.com"    # Email

# Add-on
formLink:      ""     # form Link
formID:        ""     # form ID
disqus:        ""     # Disqus ID
trackingID:    ""     # Google analytics ID

# Footer Note
footerNote:    "Everything published on this site, except as otherwise attributed, is <a href='http://en.wikipedia.org/wiki/Copyleft'>copyleft</a>. See link for info on what that means."
